### ISSUE TITLE
Star rule problem for empty input

### ISSUE THREAD

**Issue by icze** [taocpp/PEGTL#199]
Hi,

I found a further problem using  PEGTL master on fde02a1.
Here the reduced example where parsing of `empty` fails:
```
#include <tao/pegtl.hpp>
#include <tao/pegtl/analyze.hpp>
#include <tao/pegtl/contrib/parse_tree.hpp>
#include <tao/pegtl/contrib/parse_tree_to_dot.hpp>


namespace peg = tao::pegtl;

namespace grammar {

  template< char... Cs > struct padded_string : peg::pad<peg::string<Cs...>, peg::space> {};
  template< char... Cs > struct padded_one : peg::pad<peg::one<Cs...>, peg::space> {};

  struct IDENT : peg::pad< peg::identifier, peg::space > {}; // allow whitespaces
  struct name : peg::seq< IDENT, peg::star< peg::seq < padded_one< '.' >, IDENT > > > {};
  struct component_list : peg::seq< IDENT, peg::star< peg::seq < padded_one< ',' >, IDENT  > > > {};
  struct entry_list : peg::star< peg::seq < name, component_list, padded_one< ';' >  > > {};
  struct composition : peg::seq< entry_list, peg::star< peg::seq < padded_string< 'p', 'u', 'b', 'l', 'i', 'c' >, entry_list > > > {};
  struct content : peg::seq< IDENT, composition, padded_string< 'e', 'n', 'd' >, IDENT > {};


} // namespace grammar


int main(int argc, char** argv)
{
  if (peg::analyze< grammar::content >()) {
    std::cerr << "analyze() found errors in grammar." << std::endl;
    return 1;
  }

  constexpr auto empty{
    "OBJ\n"
    "end OBJ;\n"
    "\n"
  };

  constexpr auto ok{
    "OBJ\n"
    "  name0.x comp0;\n"
    "public\n"
    "  name1 compA, compB;\n"
    "end OBJ\n"
    "\n"
  };

  peg::memory_input<> in( empty, "source" );
  //peg::memory_input<> in(ok, "source");
  try {
    const auto root = peg::parse_tree::parse< grammar::content >(in);
    if (root == nullptr) {
      std::cerr << "parse() failed: root is nullptr" << std::endl;
      return 1;
    }
    peg::parse_tree::print_dot(std::cout, *root);
  }
  catch (const peg::parse_error & e) {
    const auto p = e.positions.front();
    std::cerr << e.what() << std::endl
      << in.line_at(p) << std::endl
      << std::string(p.byte_in_line, ' ') << '^' << std::endl;
    return 1;
  }

  return 0;
}
```

**Comment by d-frey** [comment]
Your input for `empty` contains a semicolon after `end OBJ`, so the grammar does not match. This is the expected behaviour.

**Comment by icze** [comment]
Oh sorry, I made a mistake while reducing the grammar. I give you an update when I have a correct reduction.

**Comment by d-frey** [comment]
The library works as expected.

Let's analyze what is happening in your case: The input is `OBJ end OBJ;  ` (if I replace newline with space, which is equivalent in this case).

Now the rules are trying to match `content = star<entry>` with `entry = seq< IDENT, composition, "end", IDENT, ";" >`. (I hope the pseudo-syntax is OK for you)

The first `OBJ` is `IDENT`. Next we try to match `composition = seq< entry_list, star< "public" > >`. Looking at `entry_list = star< name, component_list, ";" >`. And here, it matches the `end OBJ;`-part of the input. `name` matches `end` and `OBJ` matches `component_list = seq< IDENT, star<...> >`.

Now the problem is that PEGs (unlike CFGs) are truly greedy. `composition` does eat the `end OBJ;` and now `entry` can never succeed as it still expect more input to match, e.g. `end IDENT;`.

As you have put `entry` into `star<entry>` the whole `content` matches with zero entries. The matching does not consume the whole input, in fact it matches without consuming any input. (You'd need to add `eof` at the top-level grammar to ensure that no remaining input may occur).

**Comment by icze** [comment]
Thanks for your explanation, you are right. Perhaps I can make the grammar next week PEG conform (do you know some papers on this topic?) or I have to choose another library :-(. Again, thanks a lot.

**Comment by d-frey** [comment]
I'm not aware of any paper to help you with that. But in my experience the process of manually converting a grammar from a CFG into a PEG is well worth it: It can be quite involved, but at the end you learn a lot more about how CFGs and PEGs work in general as well as how your *specific* grammar is constructed.

Often times, I find that with the help of the PEGTL's convenience rules the resulting grammar is much clearer than the original CFG.

As a final hint, make sure you check out the `at<>` and `not_at<>` rules, they can be used to disambiguate branches in the grammar. Use them as a last resort, as they lead to slightly
inefficient grammars.

Good luck!
