### ISSUE TITLE
excluding some characters from string

### ISSUE THREAD

**Issue by MahaZaid** [taocpp/PEGTL#201]
Hi, 
I want to match a keyword that does not include some specific words or characters, something like using regular expression for the matched keywords. 
for example I want to match any sequence of characters that generates a word except `AND` keyword
any idea how I could do that using PEGTL?

**Comment by d-frey** [comment]
Start by having rules for your keywords:

    struct kw_and : TAO_PEGTL_STRING("AND") {};
    struct kw_or : TAO_PEGTL_STRING("OR") {};
    struct kw_origin : TAO_PEGTL_STRING("ORIGIN") {};

Then have a rule for *any* keyword:

    struct keywords : sor< kw_and, kw_origin, kw_or > {};  // not ...kw_or, kw_origin

Note that is important that in this rule, the keywords which are a prefix of another keyword are always listed in the correct order, i.e. the longer keyword needs to come first in the above `sor<...>`. This is due to the fact how PEGs work, otherwise `ORIGIN` would match the `OR` from the `kw_or` rule first and the grammar wouldn't even try to match `kw_origin'.

Finally, use the `rematch<>` rule to match an identifier and make sure it is *not* a keyword.

    struct label : rematch< identifier, not_at< keywords, eof > > {};

This should do the trick.

**Comment by MahaZaid** [comment]
okay cool, but is identifier by default includes `space` characters ? as when I try to match `test1 test2` it passes, while I want it to fail in my case.
I thought identifier supports only letters & numbers.
here is my grammar:

```
   struct kw_and : TAO_PEGTL_STRING("AND") {};
    struct kw_or : TAO_PEGTL_STRING("OR") {};
    struct keywords : sor<kw_and, kw_or> {};
    struct label : minus< identifier, keywords> {};
    struct grammar: must<label>{};
```

**Comment by d-frey** [comment]
That's just because the grammar matches the "test1" part of the input and ignores the rest. You need to explicitly enforce that the input ends after your label. Use:

    struct grammar : must< label, eof > {};

**Comment by MahaZaid** [comment]
It worked! 
thank you so much for your help :)

**Comment by d-frey** [comment]
You're welcome, thanks for choosing the PEGTL :)
