### ISSUE TITLE
Would like Chunk=1 to work for istream_input

### ISSUE THREAD

**Issue by gene-hightower** [taocpp/PEGTL#202]
I'm holding back at a3d8aebe; before the Chunk value got back-ported to version 2.x since it's not good for my applications to read even 1 byte past what the grammar needs to make the match.

In my case there often is no data available and the read will just time-out and return EOF, even though enough data has already been read to make the match.  And if the match is made the action code will do things (send data the other direction) to make even more input available to parse.

I'm not sure why PEGTL doesn't just trust the buffering in the stream (or FILE) and grab just what it needs.

Love the software and have found it very useful.  Keep up the excellent work.

**Comment by ColinH** [comment]
Do I understand correctly that you are using incremental parsing, and are having issues because there is an attempt to read more input than minimally required to satisfy the grammar?

Now I don't know what your grammar looks like, but if your parsing run ends with something like `plus< alpha >`, i.e. an unbounded repetition, then the greedy semantics of the PEG approach don't really give any other choice but to attempt to read until nothing more is available.

That said, since the PEGTL was always primarily designed for contiguous chunks of memory, and incremental parsing has always been more of an afterthought, so there might very well be room for improvement...

Can you show us the grammar and the input that exhibit the issue?

**Comment by d-frey** [comment]
GitHub is currently having some problems, but I just committed a fix. It should allow what you are looking for, although you need to set the Chunk size to 1, not 0 (reading 0 bytes makes no sense).

The PEGTL (master branch) will no longer read more than is necessary, even for UTF-8 and UTF-16. Of course, your grammar needs to make sure that it knows when to stop. If you look for a newline or a closing bracket or something, you should be fine. If you try, as Colin pointed out, to read `plus< alpha >`, it will always try to read one non-`alpha` character as it can otherwise never know whether the grammar rule is complete or not. But it sounds to me that you already understand that and your grammar will know when to stop.

I'll backport the fix to the 2.x branch later.

To explain some background: The PEGTL will always have to buffer input coming from an input stream, as we can not do backtracking in the stream and the grammar must decide when parts of the buffer can be discarded. Having a Chunk size is an important optimization, it should only be turned off (i.e. set to 1) when necessary.

**Comment by gene-hightower** [comment]
I think buffer_input::require() is asking m_reader for too many bytes.
Setting Chunk to 1.
This is a (semi-realistic) example of the problems I've been having:
[rh.cpp.gz](https://github.com/taocpp/PEGTL/files/4513830/rh.cpp.gz)

**Comment by gene-hightower** [comment]
If I go back to the pre-Chunk version (https://github.com/taocpp/PEGTL/commit/a3d8aebe15f13d92b8052470259384315dbdb250 for example) I get output from that example code like so:
$ ./rh
xsgetn(4) «BDAT»
xsgetn(1) « »
xsgetn(1) «2»
xsgetn(1) «8»
xsgetn(1) «\r»
xsgetn(1) «\n»
action<bdat> «BDAT 28\r\n»
xsgetn(4) «ABCD»
xsgetn(1) «E»
xsgetn(1) «F»
xsgetn(1) «G»
xsgetn(1) «H»
xsgetn(1) «I»
xsgetn(1) «J»
xsgetn(1) «K»
xsgetn(1) «L»
xsgetn(1) «N»
xsgetn(1) «M»
xsgetn(1) «O»
xsgetn(1) «P»
xsgetn(1) «Q»
xsgetn(1) «R»
xsgetn(1) «S»
xsgetn(1) «T»
xsgetn(1) «U»
xsgetn(1) «V»
xsgetn(1) «W»
xsgetn(1) «X»
xsgetn(1) «Y»
xsgetn(1) «Z»
xsgetn(1) «\r»
xsgetn(1) «\n»
action<anything_else> «ABCDEFGHIJKLNMOPQRSTUVWXYZ\r\n»
xsgetn(4) «BDAT»
xsgetn(1) « »
xsgetn(1) «0»
xsgetn(1) « »
xsgetn(1) «L»
xsgetn(3) «AST»
xsgetn(2) «\r\n»
action<bdat_last> «BDAT 0 LAST\r\n»
xsgetn(4) «QUIT»
xsgetn(2) «\r\n»
QUIT
xsgetn(4) «»

Compare with output from newer versions to see what I mean.

**Comment by d-frey** [comment]
Ah, yes, I missed something... hang on...

**Comment by d-frey** [comment]
Your fix was *almost* correct, but it only worked for Chunk=1. The `std::min` part has to stay, otherwise you end up corrupting your memory, as our file_stream testcase showed.

**Comment by gene-hightower** [comment]
Great!  Works just fine for me, now I can "live at head" again wrt PEGTL.

Again: great work, I thank you.

**Comment by d-frey** [comment]
You're welcome. 🙂
