### ISSUE TITLE
Can I check for the presence of a token in the middle of an input?

### ISSUE THREAD

**Issue by Nanashi-0x74** [taocpp/PEGTL#214]
I apologize for asking what seems like a basic question, this is my first parser project so I might not yet fully understand how to design a good parser, nor do I fully understand how to use PEGTL, helps and suggestions are greatly appreciated!

I am currently working to correctly parse "foo = bar", with 'foo', 'bar', and 'foo = bar' being an 'expression'

So I've written the following code:
```
// using namespace tao::pegtl;
// zseps is zero-or-more seperator

struct expression;
struct e_identifier : identifier {};

// I'm stuck here
struct e_assign : seq<expression, zseps, one<'='>, zseps, expression> {};

struct expression : sor<
	e_assign,
	e_identifier> {};
```

The current code gets stuck in e_assign's seq and expression's sor, which means it never reaches the '=' sign, which would have allowed 'seq' to determine an outcome. Is there a way to check the presence of the '=' token, being in the middle of the input?

**Comment by ColinH** [comment]
Before we look at possible fixes we can give the issue a name, your grammar is "left recursive" (you can Google "left recursion for an explanation) which is not a problem for non-deterministic grammar formalisms but does _not_ work with PEGs since it goes into an infinite loop without progress. (For the record, the grammar analysis included with the PEGTL would have detected this issue, however it does not provide solutions...) It seems that you have correctly identified the problem, matching `expression` attempts to match `e_assign`, which in turn attempts to match `expression`, ad infinitum.

**Comment by ColinH** [comment]
There are several possibilities on how to fix your grammar, partly depending on what your next steps are, i.e. how complicated the expressions are going to still become. You could take a look at the Lua 5.3 grammar in `src/example/pegtl`, in particular the comments at the beginning that explain (a bit) how I got rid of the left-recursion from the original grammar.

In your case you can observe that, for the moment, expressions are lists of identifiers separated by assignment operators. (Until you have brackets there is no way to distinguish `a = ( b = c )` from `( a = b ) = c`, so effectively you only have `a = b = c = ...`). That means you could use `list_must< identifier, one< '=' >, sep >` where `seps` is an "exactly one" version of `zseps`.

The transformation requires a bit of a change of how you think about the grammar, but with a bit of time you'll develop a feeling of how to make a grammar more "PEGgy", which in the most simple case means preferring a rule to have the form `A ( B / C )` instead of `( AB ) / ( AC )`, i.e. first make progress and then decide how to continue when there is an actual difference...

Hope this helps, at least a bit, and be sure to let us know if you get stuck again!

**Comment by Nanashi-0x74** [comment]
I see, Thank you for giving me a big lead! knowing the term makes it a lot easier to search for fixes,
I think I'll try to imitate the Lua 5.3 sample first to get a feel on PEG structure before going on my own.
A quick google search also shows me several ways to remove direct and indirect left-recursion so I'll be sure to try those where applicable.

Thank you very much!

**Comment by ColinH** [comment]
Great, happy hacking!
