### ISSUE TITLE
Action is getting called twice

### ISSUE THREAD

**Issue by iangodin** [taocpp/PEGTL#218]
I have a part of my grammar where an action is getting (unexpectedly) called twice.
Here is a small source code which shows the problem (it's C++ source code, but had to name the file .txt for github):

[test_fail.txt](https://github.com/taocpp/PEGTL/files/5176812/test_fail.txt)

I tried several variations of my grammar, but couldn't get it to work.  I do not believe the problem is with the grammar, but a bug in PEGTL (but I could be wrong)

The string being parsed is: "+a*b-"
The output of the above program is:
```
OP: "+"
ID: "a"
OP: "*"
ID: "b"
OP: "-"
OP: "-"
EXP: "+a*b-"
```
The last token '-' is getting parsed twice.
I also tried using the parse_tree::parse, and the generated AST has that last '-' token twice in the AST as well.

**Comment by ColinH** [comment]
You get two matches for `operations` at the end because the trailing `-` is first matched by the `operations` in `list<identifier,operations>` and then by the `opt<operations>` at the end of `expression`.

Somewhat more precisely, with `list<>` being implemented as
```
   template< typename Rule, typename Sep >
   using list = seq< Rule, star< Sep, Rule > >;
```
what happens is that at the trailing `-` the grammar attempts to match `star< Sep, Rule >`, here `star< operations, identifier >`, where the first rule in the `star`, `operations`, succeeds and consumes the `-`, but the second rule, `identifier`, fails, which leads to this iteration of the `star` failing and the parsing run backtracking to before the `-` before continuing after the `star` rule.

To see absolutely everything that is going on you could use the trace facility to see exactly when which rule is attempted to match where and with which outcome.

**Comment by iangodin** [comment]
It makes sense that the "-" partially matches, and then backtracks out of the list, and finally matches my optional ending.
Then the bug is probably in the parser_tree then?  I see two "-" in the resulting AST as well.
Perhaps I simplified my example too much by replacing the parser_tree::parse(...) with just parse(...).

I would expect the parser_tree to remove the "-" when it backtracks, and add it back once my second opt<operations> matches, resulting in the AST containing only one "-".  (This is the parser_tree in the contrib folder).

But thanks for the answer!  First time using pegtl, but great work!  It makes writing parser/grammars very nice.
I have been digging into the source code and am starting to understand it better, I will investigate the parser_tree further.
(I will close the question)

**Comment by d-frey** [comment]
Regarding the parse tree: Are you using the latest code from the master branch?

**Comment by iangodin** [comment]
Yes, specifically commit 7611f60c

**Comment by d-frey** [comment]
Re-opened, I was able to confirm that this is a bug in the parse tree. It is likely triggered by how `list<>` (and likely other rules) are implemented internally and how their internal backtracking is not correctly propagated in the framework, hence the parse tree itself is more-or-less correct, except that it's core assumptions are not satisfied by the convenience rules. I will need to discuss this with @ColinH.
