### ISSUE TITLE
Potential nullptr dereference under static analysis

### ISSUE THREAD

**Issue by Snape3058** [taocpp/PEGTL#222]
We have detected two potential nullptr dereference problems with our smart pointer analysis tool. 

https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/src/example/pegtl/abnf2pegtl.cpp#L728
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/src/example/pegtl/parse_tree.cpp#L174
Both cases are the unique_ptr `root`.

The corresponding execution path for the first problem is shown below. The second problem has a similar execution path apart from the first and the last event, therefore we omit it here.

If you think this may happen under some circumstances, just give us a simple confirmation of this report.

Thank you.

The execution path:

1. Calling 'parse<tao::pegtl::abnf::grammar::rulelist, abnf::selector, nothing, abnf::grammar::error_control, tao::pegtl::file_input<tao::pegtl::tracking_mode::eager, tao::pegtl::ascii::eol::lf_crlf> &, >'
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/src/example/pegtl/abnf2pegtl.cpp#L726
2. Calling 'parse<tao::pegtl::abnf::grammar::rulelist, tao::pegtl::parse_tree::node, selector, nothing, error_control, tao::pegtl::file_input<tao::pegtl::tracking_mode::eager, tao::pegtl::ascii::eol::lf_crlf> &, >'
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/contrib/parse_tree.hpp#L435
3. Calling 'parse<tao::pegtl::abnf::grammar::rulelist, nothing, internal::make_control<node, selector, error_control>::template type, tao::pegtl::apply_mode::action, tao::pegtl::rewind_mode::required, tao::pegtl::file_input<tao::pegtl::tracking_mode::eager, tao::pegtl::ascii::eol::lf_crlf> &, tao::pegtl::parse_tree::internal::state<tao::pegtl::parse_tree::node> &>'
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/contrib/parse_tree.hpp#L420
4. Conservative call: tao::pegtl::parse_tree::internal::make_control<tao::pegtl::parse_tree::node, selector, error_control>::state_handler<tao::pegtl::abnf::grammar::rulelist, false, false>::match
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/parse.hpp#L27
5. Returning from 'parse<tao::pegtl::abnf::grammar::rulelist, nothing, internal::make_control<node, selector, error_control>::template type, tao::pegtl::apply_mode::action, tao::pegtl::rewind_mode::required, tao::pegtl::file_input<tao::pegtl::tracking_mode::eager, tao::pegtl::ascii::eol::lf_crlf> &, tao::pegtl::parse_tree::internal::state<tao::pegtl::parse_tree::node> &>'
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/contrib/parse_tree.hpp#L420
6. Assuming the condition is true, taking true branch
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/contrib/parse_tree.hpp#L420
7. Pointer assignment: const class std::unique_ptr<struct tao::pegtl::parse_tree::node, struct std::default_delete<struct tao::pegtl::parse_tree::node> > root = nullptr
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/contrib/parse_tree.hpp#L421
8. Returning from 'parse<tao::pegtl::abnf::grammar::rulelist, tao::pegtl::parse_tree::node, selector, nothing, error_control, tao::pegtl::file_input<tao::pegtl::tracking_mode::eager, tao::pegtl::ascii::eol::lf_crlf> &, >'
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/contrib/parse_tree.hpp#L435
9. Returning from 'parse<tao::pegtl::abnf::grammar::rulelist, abnf::selector, nothing, abnf::grammar::error_control, tao::pegtl::file_input<tao::pegtl::tracking_mode::eager, tao::pegtl::ascii::eol::lf_crlf> &, >'
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/src/example/pegtl/abnf2pegtl.cpp#L726
10. Dereference an empty smart pointer by calling operator ->
https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/src/example/pegtl/abnf2pegtl.cpp#L728

**Comment by d-frey** [comment]
Your tool is wrong because it doesn't see the whole picture. Both cases can not happen under any circumstances, although the reasoning is slightly different. The main argument is that parsing in general can return with three results:

1) success
2) local failure
3) global failure

The first case is obviously not a problem, as `root` will not be empty and can be dereferenced. The third case is also not a problem, as the lines your static analysis tool found will be skipped (there is a `try`/`catch`-block handling the exception).

The question therefore is: Can the second case occur? In general, when the main parse method results in local error, it returns `false`. For the parse tree's parse method, this leads to returning an empty pointer. But in both cases this can not happen.

Look at the top-level grammar rule for the second example you found first. The parser is called with `example::grammar`, which is a `must`-rule. That rule ensures that it either returns `true` (success) or it throws an exception. Local failure is simply not possible.

The same is valid for `abnf2pegtl`, although it is more complicated to see: The top-level rule is basically whitespace + rules. And when it expects a rule and whatever it finds is not a valid rule, at first glance it does yield local error. But now the local error triggers a global error, i.e. it is converted to an exception (see https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/src/example/pegtl/abnf2pegtl.cpp#L313).

**Comment by d-frey** [comment]
BTW: What static analysis tool did you use?

**Comment by Snape3058** [comment]
Thank you for your reply. 

If I got you right, you mean our tool reported a real problem that will never truly happen in the real world.

Our tool is a research tool focusing on smart pointer errors developed on the top of the Clang Static Analyzer (CSA). Currently, it is just an experimental demo and I am now doing tests and evaluations on it for my research paper. Since it is developed on the top of CSA, it has many problems that the CSA also has (e.g. lacking some cross translation unit information). Although we have tried our best to fix some, some of the problems may also affect the analysis results and we cannot fix them all.

If you would like to help us improve it, could you please provide us some **real** smart pointer errors that you have corrected during your development?

Thank you.

**Comment by d-frey** [comment]
> If I got you right, you mean our tool reported a real problem that will never truly happen in the real world.

That makes it sound as there is an actual problem and I just think it is *unlikely* to happen in practice. That is not the case. There is no problem. Even in theory there is absolutely no way that you can trigger this with any input whatsoever. (unless, of course, you change the program)

Your tool doesn't look deep enough. This is admittedly hard to do, but for the example of `parse_tree.cpp` your tool sees line 420 and 421 (from `parse_tree.hpp`), where 421 returns `nullptr`. This is based on the assumption that the call to `TAO_PEGTL_NAMESPACE::parse< Rule, ... >( ... )` in line 420 returns `false` (which is then negated in the if-expression). Looking at the top-level `Rule` in `parse_tree.cpp`, that rule is `must< ... >`. Looking at the definition for `must<>` (after skipping some intermediate template instances that only forward results), you end up here: https://github.com/taocpp/PEGTL/blob/20663bcb78c0cc094a0d19b85f3b41db505f3929/include/tao/pegtl/internal/must.hpp#L50-L56

As you can see, `must<>` either raises an exception or it returns `true`. It *never* returns `false`.

Similar, but way deeper analysis will reveal the same to be true for the case of `abnf2pegtl.cpp`.

Again, your tool did not find a problem, it is a false positive. If you can not prove that the if-condition can actually be met, then don't report a problem. IMO static analysis tools should have a near-zero false positive attitude.

> Our tool is a research tool focusing on smart pointer errors developed on the top of the Clang Static Analyzer (CSA). Currently, it is just an experimental demo and I am now doing tests and evaluations on it for my research paper. Since it is developed on the top of CSA, it has many problems that the CSA also has (e.g. lacking some cross translation unit information). Although we have tried our best to fix some, some of the problems may also affect the analysis results and we cannot fix them all.

The PEGTL is, by design, working with templates in a single translation unit, hence the above reasoning I gave should be possible for the tool to see. Obviously, it is much more complicated to analyze it than just looking at the limited code path in your initial report.

> If you would like to help us improve it, could you please provide us some **real** smart pointer errors that you have corrected during your development?

I don't recall any specific problems that we had wrt smart pointers. If there was a problem with a nullptr deference, it was usually depending on broken invariants about the rules themselves and how they interact with each other and the framework, but looking at the smart pointers would not lead you to the root cause of the problem.

**Comment by Snape3058** [comment]
OK, thank you for your help and apologize for disturbing you.
