### ISSUE TITLE
Exceptionless PEGTL

### ISSUE THREAD

**Issue by ColinH** [taocpp/PEGTL#251]
As mentioned in e.g. #250 it would be useful for some users to identify and enforce the (large) subset of the PEGTL that is compatible, or can be made compatible, with `-fno-exceptions`.

**Comment by ColinH** [comment]
The core PEGTL already contains very few `throw` and `try-catch` statements, so it shouldn't be too much work.

**Comment by ColinH** [comment]
We can use the presence or absence of the `__cpp_exceptions` macro to enable or disable exceptions and related behaviour.

(And hope that all compilers correctly support it, at least the ones with enough C++17 support for us.)

**Comment by d-frey** [comment]
I just checked and `__cpp_exceptions` is supported on GCC, Clang, and MSVC in all versions of those compilers that the PEGTL supports. I'll give it a try...

**Comment by d-frey** [comment]
@Raekye Any suggestion what I should do when I can't throw an exception but I can't continue either? `std::abort()`? Print to `std::cerr` before calling `std::abort()`?

**Comment by d-frey** [comment]
I've added a branch `no-exception`. What I've done so far is:

* Adapt the core to `static_assert` when you try to use anything that requires exceptions. Like `raise`, `must`, ...
* Print to `stderr` and `abort()` when opening files or wrongly reading from a streams or a buffered input goes wrong.
* Adapt `contrib/control_action.hpp`.

What I haven't done / what won't work:

* I haven't adapted any tests, our test framework, or any examples. Use your own code to test.
* No adaption of `contrib/integer.hpp`.
* No adaption of `contrib/unescape.hpp`.

@Raekye I'd appreciate if you could have a look, test if works for you and review my attempt to support `-fno-exceptions`. If you like, please also join our Discord to speed the discussion up, I'll also let others know that we are working on support for `-fno-exceptions`.

**Comment by Raekye** [comment]
> Any suggestion what I should do when I can't throw an exception but I can't continue either? `std::abort()`? Print to `stdout`/`stderr` before calling `std::abort()`?

Based on [GCC's libstdc++](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_exceptions.html) it seems that either `abort` or `std::terminate` get called when an exception is thrown in code compiled with `-fno-exceptions`. It's not clear to me which one, since one code snippet shows the C `abort`, while it also says under C compatibility:

> In particular, unwinding into a frame with no exception handling data will cause a runtime abort. If the unwinder runs out of unwind info before it finds a handler, `std::terminate()` is called.

[This stack overflow thread](https://stackoverflow.com/questions/2820285/abort-terminate-or-exit) says:

> `std::terminate` is what is automatically called in a C++ program when there is an unhandled exception.

Although I didn't see a source (referring to either the C++ specification, GCC, Clang, or MSVC documentation). But I've seen other people say it's `std::terminate` that gets called, in a few other threads/places as well. From the same stack overflow thread as above, it seems that `std::terminate` is a higher level C++ abstraction than `std::abort` which raises the POSIX signal `SIGABRT`, so I think that's preferable (although I can do more research).

As for printing a message, I feel it's "cleaner" to simply call terminate/abort. But since exceptionless PEGTL will be a new thing, nobody should have any expectations/dependencies on the exact behaviour. Printing a PEGTL-unique message before terminate/abort will help users find the relevant documentation. Also, it's not like I/O had failed, so printing should be safe

**Comment by d-frey** [comment]
I've replace `std::abort` with `std::terminate`, although I think that maybe we should handle this more gracefully. But it is too early to care more about these cases right now.

Instead, I also relaxed some of the requirements for `-fno-exceptions`, you can now use `unwind()` and instead of breaking the compile, we simply assume it will never be called (as there can never be an exception that could trigger it). This means that the tracer (and possibly other features) are now available with `-fno-exceptions`.

I will continue on the weekend, let's see how far we can push the core before worrying about file/buffered inputs.

**Comment by d-frey** [comment]
I've merged the branch into master. Current status:

You can use the PEGTL normally, everything should work as expected. However, there are parts of the library that rely on exceptions and therefore can't be used.

* When trying to use the following rules in your grammar, a `static_assert()` will fire:
  * `raise<>`
  * `try_catch<>`
  * `try_catch_type<>`
  * `must<>`
  * `if_must<>`
  * `if_must_else<>`
  * `list_must<>`
  * `opt_must<>`
  * `star_must<>`
* You can't use the following grammars from contrib as they use the above rules:
  * HTTP
  * JSON
  * URI
* The following utilities from contrib use exceptions or the above rules:
  * `integer.hpp`
  * `raw_string.hpp`
  * `unescape.hpp`

While the above rules, features, etc. will abort the compilation, there are a few input classes that are affected:

* `buffer_input`
* `read_input`
* `file_input`
* `mmap_input`
* `cstream_input`
* `istream_input`

The above inputs will work normally, unless they run into a problem. Where the PEGTL would normally report the problem with an exception, it will now print an error to `stderr` and terminate the program.

The tests and examples have been adapted where possible, but currently multiple tests and examples are broken and won't compile (as they rely on the above mentioned rules, etc.) For that reason, there is also no CI job for `-fno-exceptions` right now.

Next steps:

* Fix or disable as many tests and examples as necessary and add a CI job to ensure future stability of this feature.
* Consider fixing the grammars and the utilities in contrib to not rely on exceptions.
* Don't terminate when a stream or file input runs into a problem? What else could we do?

**Comment by d-frey** [comment]
- [ ] `integer.hpp`
- [ ] `raw_string.hpp`
- [ ] `unescape.hpp`
- [ ] HTTP
- [ ] JSON
- [ ] URI

**Comment by d-frey** [comment]
For now, I won't adapt the HTTP and URI grammars and `contrib/integer.hpp`. The rest is now usable with exceptions disabled. I've just added the CI job and most tests will work (some have #ifdef's to disable some tests depending on exceptions).

**Comment by ColinH** [comment]
And that should conclude this round of supporting `-fno-exceptions`.

**Comment by d-frey** [comment]
Almost. Documentation, anyone? ;)

(And I'm still working a bit on the examples of which some are currently broken)
