### ISSUE TITLE
file_input write-locks its file

### ISSUE THREAD

**Issue by s9w** [taocpp/PEGTL#257]
At least under Win10, the `file_input` prevents its file from being written by a text editor (or probably any other process). While I'm sure that's safer on the parsing side of things, @ColinH said in discord it's not intentional and up to the more or less third party code provided. I dug a bit into it and it seems these two lines seem the be the cause:

https://github.com/taocpp/PEGTL/blob/8c1f74f0f5a5d44a32561a94d42c183e417b35c3/include/tao/pegtl/internal/file_mapper_win32.hpp#L83

https://github.com/taocpp/PEGTL/blob/8c1f74f0f5a5d44a32561a94d42c183e417b35c3/include/tao/pegtl/internal/file_mapper_win32.hpp#L99

According to the [windows docs](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfile2), the here missing `FILE_SHARE_WRITE` parameter to `CreateFile2()` is described with:

> `FILE_SHARE_WRITE`: Enables subsequent open operations on a file or device to request write access. **Otherwise, other processes cannot open the file or device if they request write access**.

So I think it would be wiser to change this to `FILE_SHARE_READ | FILE_SHARE_WRITE`. I tried it locally and it works like a charm. I am however unfamiliar with this function, hence the cautious suggestion rather than a pull request.

edit: Actually not sure about the second location. I just saw that's a call to another function and that branch of the macro isn't evaluated on my machine.

**Comment by d-frey** [comment]
Both calls are similar enough that I would just keep them in sync - whatever works for one of them should work for the other.

What I am wondering is whether we should actually allow write access for other processes to a file *while we are parsing it*. That seems dangerous as the parser might get confused, especially when backtracking. Imagine `at<X>` working and then `X` not working. This might even result in crashes (or worse). Are we sure we want to allow it?

**Comment by s9w** [comment]
Naively I would say copy the contents into memory, release the actual file and then parse that copy. The problem with file locking I ran into was that I was debugging my program, discovered that the error was really in the parsed file and wanted to change it (while the program was still running so I could just hit restart once the mistake is fixed). I can see the case for actual locking however.

**Comment by d-frey** [comment]
In that case you should simply use `read_input<>` instead of `file_input<>`. The latter only mmaps the file into memory (if supported by your OS, but that is usually the case). `read_input<>` is meant as a fallback and it does exactly what you want: It reads the file into memory and releases the handle immediately. The reason to use mmap by default is that it is far more efficient and allows for extremely large files to be parsed.

**Comment by s9w** [comment]
I didn't know about read_input - my bad, sorry. I guess that only leaves the question if that file locking works the same across all platforms. But my own issue with this is solved.

**Comment by d-frey** [comment]
No worries, we don't expect most users to know about `read_input<>`. The default input for reading files is `file_input<>` which, if you look at https://github.com/taocpp/PEGTL/blob/master/include/tao/pegtl/file_input.hpp, is either `mmap_input<>` (if available) or `read_input<>` otherwise. This should work for 99% of our users, but you are one of those users who have special requirements/wishes and so it's fine to ask and we are happy to point you to `read_input<>`.

And you are right, we should check if the mmapped input on Linux/macOS could/should have a write-lock. I'll discuss this with @ColinH.

**Comment by ColinH** [comment]
IMHO having the `mmap_input` lock the file on Linux or macOS would be counter-intuitive, unlike on Windows it's not something one would expect. And then there's the question of which kind of locking to use. At most we could extend the API to read from or mmap a user-supplied file descriptor so that they can perform locking if they want to. That said, nobody's missed it so far...
