### ISSUE TITLE
parse tree for contrib/uri is incorrect for userinfo

### ISSUE THREAD

**Issue by kelvinhammond** [taocpp/PEGTL#260]
I attached it, its huge and I can't upload svg files to github, I tried it with `http://de.wikipedia.org/wiki/Uniform_Resource_Identifier`.

As you can see in the screenshot below the userinfo is set as `de.wikipedia.org`. I'm writing a uri parser and I was using contrib for this. I think the action may be running twice after a backtrack, how would I avoid this?

```c++
const char* uri_str = "http://de.wikipedia.org/wiki/Uniform_Resource_Identifier";
pegtl::memory_input in(uri_str, "");
auto root = pegtl::parse_tree::parse<grammar::URI>(in);
if(root) {
  pegtl::parse_tree::print_dot(std::cout, *root);
}
```

**There is an image right below this:**
![uri_parse_tree](https://user-images.githubusercontent.com/1824682/113234089-98a5e980-926e-11eb-8cd5-d5d780a2d265.png)

**Comment by d-frey** [comment]
I don't see it. The attached picture shows a node "opt_userinfo" which is empty (as opt<> always matches) and which has no children, hence "userinfo" never matched and there is no node for it.

**Comment by kelvinhammond** [comment]
I think I've figured it out. Parse tree works because during backtracking it overwrites previous elements where my struct
```c++
struct uri {
  std::string_view userinfo;
  std::string_view host;
};
```
does not overwrite the `userinfo` during backtracking. Is there a way to handle this situation?

**Comment by d-frey** [comment]
The actions called during a parsing run are called immediately when a rule matched, even when a higher-level construct fails afterwards. This can lead to actions being called multiple times or other often unexpected results for beginners. There is no general solution to this as each approach has different pros and cons, especially wrt performance. Sometimes, people are able to rewrite their grammars, e.g. from `sor<seq<a,b>,seq<a,c>>` to `seq<a,sor<b,c>>`. Sometimes you add some flags to your structures, sometimes you might add additional actions which can clear our other parts of your data structures.

As this topic comes up quite often, maybe we could improve the documentation for this a bit and add some examples on how to handle the situation with different techniques? What do you think, @ColinH ?

**Comment by ColinH** [comment]
There are many ways to work around this issue, which one works best depends on how much you might be willing to change the grammar and on how exactly your actions work and which rules they are attached to.

The root of the issue here is that there are inputs (parts of an input) that match `host` also match `userinfo`, and the disambiguation is done by the `one< '@' >` rule in `opt_userinfo`.

What is needed here is a way to either undo whatever the action on `userinfo` did when the `one< '@' >` does not match, or a way to only actually do something for `userinfo` after matching the `@` which confirms that it's not a `host`.

So one possibility would be to let the action for `userinfo` put the matched input into some temporary string and only move it into the final intended destination in the action for `one< '@' >`.

**Comment by ColinH** [comment]
@d-frey Great, we answered at the same time :-)

So that would be a new paragraph or section in "Actions and States"?
