### ISSUE TITLE
Is there  performance data for PEGTL

### ISSUE THREAD

**Issue by Winging** [taocpp/PEGTL#261]
I am considierring using pegtl in my project and I am looking for  the performance data. Where can I find it?

**Comment by ColinH** [comment]
Do you mean benchmarks? It's not so easy to benchmark parser libraries because the results will depend on the grammar and on how well you play to the strengths of each library. The PEGTL is built to be fast without going beyond the point where higher performance requires (much) higher complexity rather than simplicity. Unless you have some very special requirements it will probably be fast enough for you, and I'd expect that you'd probably have a hard time trying to find something as universal and stable that is noticeably faster. But, by all means, let us know if you find something that significantly outperforms the PEGTL, it would be interesting to see how it works. And please let us know if you make or find any benchmarks, again I'd be curious to see the results.
