### ISSUE TITLE
support for bit-aligned parsing

### ISSUE THREAD

**Issue by katachinao98** [taocpp/PEGTL#263]
Hello PEGTLers :)

Is there any possibility to support consuming data bits instead of bytes at a time?

I am parsing files that are mostly long streams of byte-aligned fields, but sometimes includes smaller bit sequences. I can't see any easy way to do this with PEGTL, which works very well for the byte-aligned parts.

**Comment by ColinH** [comment]
This is currently not possible, sorry. The unit of consumption (and rewinding) in the input layer is the byte, and we can't easily change that.

(In particular because you'd expect all byte-based rules to still work with a bit-based input, so the change to bits needs to be somehow backwards-compatible with those rules, which is unlike a token-based input for which we have a very basic example that isn't perfect but does work to some extent.)

We'll try to keep bit-based inputs in mind if and when we refactor the input layer to be more generic...

Until then, if you continue to use the PEGTL, I'm afraid you'll have to make do with some custom-rules for the bit sequence parts. If these bit sequence parts always start and end on a byte border then you could probably do a set of atomic rules that use a small integer in the States to keep track of how many bits of the current byte have already been consumed. If you then write a `peek_bits()` function similar to the other peek-functions, and a corresponding `bump()`, it might be relatively easy to implement bit-based versions of the atomic rules for binary data found in `include/tao/pegtl/contrib/uint8/16/32/64.hpp` etc.

If you can share some more details about the size and structure of these bit-based parts, and possibly how you have implemented parsing them, that might help.
