### ISSUE TITLE
Recursive rules and converting a bison grammar to PEG?

### ISSUE THREAD

**Issue by ethindp** [taocpp/PEGTL#283]
I'm trying to port a bison grammar to a PEG hopefully using this library. The problem is that the grammar (in bison) uses a lot of recursion and I'm not really sure how to address it, and it also references rules that are defined (later) in the grammar. This conflicts with C/C++'s rule of "something must be defined before its used".

An example of this is the first couple rules of the grammar:

```ebnf
program ::= statements

statements ::= nothing
    | statements statement

statement ::=
    if_statement
    (* ... *)

if_statement ::= if ( expression ) statements [{elseif ( expression ) statements }] [else statements] endif
```

(This isn't how its written in bison, but its approximate EBNF representation.)

I'm also unsure how to translate bison directives like:

```bison
%right  '='
%nonassoc '?' '|'
```

or even if these directives even matter. What's the best strategy for approaching this process without feeling like I'm taking on too much at once?

**Comment by ColinH** [comment]
There are several issues that you address, let's start with something simple to get you going.

Recursion is possible if you add forward declarations, see https://en.cppreference.com/w/cpp/language/class for a more in-depth explanation, thereby telling the compiler "I don't know what exactly this type will look like, but assume that it exists and trust that it will be defined later".

```
struct bar;  // Forward-declaration of struct bar.
struct foo : tao::pegtl::seq< tao::pegtl::digit, bar > {};
struct bar : tao::pegtl::seq< tao::pegtl::alpha, foo > {};
```

(If it were the case that `foo` referenced a rule `bar`, but not vice versa, one should first define `bar` and then `foo` in order to minimise the number of required forward declarations.)

**Comment by ColinH** [comment]
Once you have your recursion up-and-running you need to take care of *left recursion*. You should look for some discussions of the subject to learn about what that is, and how to eliminate it.

Elimination is necessary because the deterministic straightforward semantics of PEGs handle left recursion differently than CFGs with their non-determinism.

The PEGTL grammar analysis, see https://github.com/taocpp/PEGTL/blob/main/doc/Grammar-Analysis.md, can help you determine whether your grammar still contains left-recursion and other similar issues.

Feel free to ask more questions here, this is a subject that usually takes some time and experience to get comfortable with. There are also a couple of examples of where this transformation has been done right here in the PEGTL, most notably https://github.com/taocpp/PEGTL/blob/main/src/example/pegtl/lua53.hpp.

**Comment by ColinH** [comment]
For how to handle operators with their precedence and associativity you can look at https://github.com/taocpp/PEGTL/blob/main/src/example/pegtl/expression.cpp, however it might be useful to first read up on one of the standard algorithms for this task. An alternative approach is to hard-wire the operators into the grammar as I did in the Lua 5.3 example referenced in the commend above. I hope this doesn't seem too daunting, you *do* seem to be taking on a lot at once, so remember "divide and conquer" and "small steps" to not take on everything at once.

**Comment by ethindp** [comment]
@ColinH Thank you so much, I wasn't sure if I'd have to somehow "flatten" the grammar or whether PEGs supported that kind of recursion or not. I like how the grammar analysis tells you if your grammar has left recursion or not. I was attempting to follow the Wikipedia article on [left recursion](https://en.wikipedia.org/wiki/Left_recursion) but I'm still confused on exactly how to get rid of it. I'd appreciate help on that but I'll also keep trying to figure it out for myself. :) Thank you for all the help -- I'd love to try writing my own language just for fun!

**Comment by ColinH** [comment]
If you search the web you will find many examples of how to eliminate left recursion, and while not all of them are very understandable you should find something useful.

**Comment by mgood7123** [comment]
does pegtl support infinite recursion?

**Comment by d-frey** [comment]
The PEGTL itself does not have any direct recursion limits, but of course given the recursive nature of the generated code, the stack size will limit the recursion.

We added an optional limiter for the recursion depth to contrib, see https://github.com/taocpp/PEGTL/blob/main/doc/Contrib-and-Examples.md#taopegtlcontriblimit_depthhpp

Documentation is... well... limited, but the example at https://github.com/taocpp/PEGTL/blob/main/src/test/pegtl/limit_depth.cpp hopefully helps. The advantage of our approach is, that it can be more efficient than a general limiter that is applied to all rules.

**Comment by ColinH** [comment]
The `until<>` rule included with the PEGTL is implemented with iteration, not recursion, and can therefore handle arbitrarily large inputs without filling the stack.

**Comment by d-frey** [comment]
To add to @ColinH's comment: If we offer a (convenience) rule, it is often implemented more efficiently than a naive approach. That includes skipping stack frames, double matching of subrules or even replacing recursion with iteration. Therefore, before rolling your own version always check what we already offer. :)

**Comment by mgood7123** [comment]
ok :)

**Comment by ColinH** [comment]
If there are any further questions regarding this subject please feel free to ask here, or open a new issue or discussion.
