### ISSUE TITLE
Handling Whitespace

### ISSUE THREAD

**Issue by computerquip** [taocpp/PEGTL#297]
I'm not clear on how to cleanly handle whitespace. It seems in most of the examples, it manually creates a space rule and inserts the rule onto the right side of every other sequence. Is there a better way of handling skipping whitespace?

**Comment by skyrich62** [comment]
Hi, in Parser Expression Grammars, (PEG), there is usually no lexical pass or phase.  You specify whitespace rules exactly as any other.  So, the examples you see **are** the preferred way of dealing with whitespace.

Basically, each rule should handle its own internal whitespace.

Consider a limited set of C/C++ statements: 
I've added comments which detail the PEG from which the PEGTL structs are formed. Assume a reasonable implementation of "expression".

```c++
// EQUALS <- '='
struct EQUALS : one< '=' > { };

// SEMI <- ';'
struct SEMI : one< ';' >{ };

// A C++ style one-line comment. two consecutive slashes followed by anything up to the end of line or end of file.
// line_comment <- '/' '/' .*
struct line_comment : 
    seq< two< '/' >, until<eolf> >
    { };

// A single space or a line_comment.
// ws <- space / line_comment
struct ws :
    sor< space, line_comment >
    { };

// Zero or more spaces or line_comments
// wss <- ws*
struct wss :  star< ws > { };

// At least one space or line_comment.
// wsp <- ws+
struct wsp : plus< ws > { };

// assignment_statement <- identifier '=' expression ';'
struct assignment_statement :
    seq< identifier, wss, EQUALS, wss, expression, wss, SEMI >
    { };

/// expression_statement <- expression ';'
struct expression_statement:
    seq< expression, wss, SEMI >
    { };

// statement <- assignment_statement / expression_statement
struct statement :
    sor< assignment_statement, expression_statement >
    { };

// A list of statements
// statement_list <- statement+
struct statement_list : plus< statement, wss > 
    { };

// The top-level grammar
// grammar <- statement_list EOF
struct grammar : 
    seq< wss, statement_list, eof >
    { };
```

Each production rule handles its own whitespace internally.  In this case, "grammar" is the top-level grammar.  First it matches and consumes any amount of leading whitespace, then it matches a statement_list, then it matches the end of input.

statement_list matches at least one statement followed by any amount of whitespace.  Notice that this will consume any amount of whitespace after each statement,  Thus, there is no need to consume any whitespace in the "grammar" rule after consuming the statement_list.

The "statement" rule has no internal whitespace, (it defers that to the individual statement kinds).

"assignment_statement", and "expression_statement" each handle their own internal whitespace.

This is "The Right Way(tm)" of doing things in PEGs in general, and in PEGTL in particular.

Having said that, it's **possible** to create a lexical pass, and feed tokens, rather than raw input to PEGTL, but that's another discussion, (See issue #250)

**Comment by computerquip** [comment]
That's a clean explanation (with code no less) which I appreciate. I'll give this a try for now and close the issue.

**Comment by ColinH** [comment]
@skyrich62 Couldn't have said it better, thanks!

@computerquip Hope this works for you!
