### ISSUE TITLE
input reparse

### ISSUE THREAD

**Issue by mgood7123** [taocpp/PEGTL#298]
is it possible to reparse a given input? and if so, how?

for example, consider the following input

```
Y(X)(z)
```

`Y(X)` gets parsed and the action determines that it should get replaced with `X`

it should now cancel the current parsing/line and parse with a new input of `X(z)`

assuming a `line-based` grammar

for example

```
1: grammar plus<sor<letter, space, newline, func>>  -> input "Z A(b)(c)\nB"
1: grammar letter -> match "Z"
1: grammar space -> match " "
1: grammar func -> match "A(b)" -> substitute `E`
1: // how do i cancel grammar and rematch?
1: grammar plus<sor<letter, space, func>>  -> input "E(c)\nB"
1: grammar func -> match "E(c)" -> no substitution
1: grammar newline -> match "\n"
2: grammar letter -> match "B"
```

and in the case of a pipe or input stream i assume the input would be buffered somehow to support backtracking of failed matches

if so then it would stand within reason the buffer may be

```
// "Z A(b)(c)\nB"
letter -> "Z" // grab "Z"
// " A(b)(c)\nB"
space -> " " // grab " "
// "A(b)(c)\nB"
func -> "A(b)" // grab "A(b)"
// "(c)\nB"
// replace buffer with "E" and rescan
func -> "E(c)" // grab "(c)"
// no substitution
// "\nB"
newline -> "\n" // grab "\n"
// "B"
letter -> "B" // grab "B"
// ""
```

**Comment by ColinH** [comment]
So you want to re-parse not the input but a modified version of the input. Can you explain at a higher level what you are trying to achieve, i.e. a description of the problem without jumping straight into the solution?

**Comment by mgood7123** [comment]
> So you want to re-parse not the input but a modified version of the input. Can you explain at a higher level what you are trying to achieve, i.e. a description of the problem without jumping straight into the solution?

i am writing a macro preprocessor and i need to implement input-rescan, where the input should be re-evaluated and rescanned after each macro expansion that takes place

eg `A(b)(c)` -> at function -> parse function -> expand function-like macro `A(b)` to `E` -> `E(c)` -> at function -> parse function -> ...

for example

```
#define X(a) a y
#define Y(Z) Z
Y(X)(z)

// Y(X) -> X
// X(z) -> z y
```

**Comment by mgood7123** [comment]
maybe there should be a temporary input stream that can be written to in order to temporarily push input to be read from instead of the main input stream?

eg

`Y(X)(z)` -> secondary input is empty -> read `Y(X)` from main input stream -> `Y(X)` matches a grammar -> append `X` to secondary input stream

`(z)` -> secondary input contains data -> read `X` from secondary input stream -> secondary input is empty -> read `(z)` from main input stream -> `X(z)` matches a grammar

**Comment by ColinH** [comment]
Just to be sure, you need the text-level substitution semantics of the macros (which prevents an alternative higher-level semantics)?

**Comment by mgood7123** [comment]
yes

**Comment by mgood7123** [comment]
im currently attempting to write my own parser that can do this but i am not sure how to go about implementing automatic backtracking and rule capture

**Comment by ColinH** [comment]
As noted in #290 the PEGTL does not and does not want to support modifying inputs because this would break some important invariants and make it impossible to have error reporting that includes the original input leading to the error.

I don't know what a good approach to handle text-level macros with the PEGTL is since I never implemented one (at the moment I'd strongly prefer a more higher-level macro approach that operates on the AST and that doesn't require re-parsing).

It would probably expand the top-level macro invocations into a temporary buffer that is used until all macros are resolved, and then use the temporary buffer to modify the stream of tokens coming out of the first stage of the parser.

(While PEGs usually don't have a separate lexer my gut feeling is that it might be beneficial to have one when doing this kind of macro processing.)

We are currently working on a generalisation of the PEGTL inputs that would make it easier to parse, say, a `std::vector< my_token >` that was generated by a lexer which would make that easier.

**Comment by mgood7123** [comment]
alright
