### ISSUE TITLE
Why parsing succeeds?

### ISSUE THREAD

**Issue by dprogm** [taocpp/PEGTL#323]
I have defined a fairly simple grammar that should match an object which is defined as a comma separated list of key-value-pairs.

```cpp
struct Key
  : tao::pegtl::pad<
      tao::pegtl::identifier,
      tao::pegtl::space
    >
  { };

struct Value
  : tao::pegtl::pad<
      tao::pegtl::identifier,
      tao::pegtl::space
    >
  { };

struct KeyValuePair
  : tao::pegtl::seq<
      Key, tao::pegtl::one<':'>, Value
    >
  { };

struct KeyValuePairs
  : tao::pegtl::list<
      KeyValuePair, tao::pegtl::one<','>
    >
  { };

struct Object
  : tao::pegtl::seq<
      tao::pegtl::one<'{'>, KeyValuePairs, tao::pegtl::one<'}'>>
  { };
```

My expectation is that parsing only succeeds for inputs like:
```
{ Key1 : Value1 , Key2 : Value2 }
```
but it also succeeds for inputs like:
```
{ Key1 : Value1 , Key2 : Value2 } }
```
Note the extra `}` at the end. Why it behaves like this and how can I fix it in my grammar?

**Comment by ColinH** [comment]
Because there is no implicit requirement to match _all_ of the input in a successful parsing run. Your grammar matches a part of the input and then is done, successfully. If you add a `tao::pegtl::eof` or `tao::pegtl::eolf` rule at the end of the `seq` in `Object` it shouldn't accept the input with the second curly brace anymore.

**Comment by dprogm** [comment]
Thank you for the fast response. That works as expected. Can be closed.

**Comment by ColinH** [comment]
Good to hear. Happy hacking!
