### ISSUE TITLE
Inconsistent behaviour of `sor` for custom rules.

### ISSUE THREAD

**Issue by aneax** [taocpp/PEGTL#360]
https://godbolt.org/z/7he8WWq94

[example.txt](https://github.com/taocpp/PEGTL/files/14842688/example.txt)

In the code attached, even when `ConsumerAction` does nothing other than define `apply` functions.
The behavior of the parse calls as below differ.

```c++
pegtl::memory_input<> in("local\n", "from_memory");
// completes successfully.
auto success = pegtl::parse<rules::Top<CustomConsumer>, ConsumerAction>(in);
//
in.restart()
// fails to parse.
auto success = pegtl::parse<rules::Top<CustomConsumer>, pegtl::nothing>(in);
```

The problem seem to be comming during `sor` but only for the custom rule I implemented.  The code below works as expected on both parse calls.
```c++
// same custom rules directly implemented.
struct PEGGlobal : pegtl::sor<TAO_PEGTL_ISTRING("global")> {};
struct PEGLocal
    : pegtl::sor<TAO_PEGTL_ISTRING("local"), TAO_PEGTL_ISTRING("loc")> {};
// top level rules.
struct CustomConsumer : pegtl::sor<PEGGlobal, PEGLocal> {};
```

The code path seems to deviate due to this variable affecting the rewind mode.
https://github.com/taocpp/PEGTL/blob/3c6e0e092ca77868ea3a0b0f47b5948dc07c1c86/include/tao/pegtl/match.hpp#L138

Is this happening due to violation some underlying assumption by my custom rule?

**Comment by ColinH** [comment]
Is it possible that your custom rule doesn't follow the "prime directive" for PEGs, that a rule that returns `false` doesn't consume input?

**Comment by ColinH** [comment]
```c++
template <ConsumerKind Kind>
struct ConsumerKeyword {
    template <tao::pegtl::apply_mode A, tao::pegtl::rewind_mode M,
              template <typename...> class Action,
              template <typename...> class Control, typename ParseInput,
              typename... States>
    static auto match(ParseInput &&in,
                      [[maybe_unused]] States &&...states) -> bool {
        auto m = in.template auto_rewind< M >();
        auto next = next_keyword<A, M, Action, Control>(in);
        if (!next.empty()) {
            auto kind = to_consumer_kind(next);
            auto pos = in.position();
            auto success = (kind == Kind);
            std::cout << " - Expected: " << std::quoted(to_string_view(Kind))
                      << ", From stream: " << std::quoted(next) << " at "
                      << pos.source << ":" << pos.line << ":" << pos.column
                      << " -> Success: " << std::boolalpha << success << "\n";
            return m( success );
        }
        return m( false );
    }
};
```

**Comment by ColinH** [comment]
If you're not on the `main` branch but on a 3.x version the line that defines and initialises `m` must read
```c++
         const auto m = in.template mark< rewind_mode::required >();
```
and the call to `next_keyword()` must use `tao::pegtl::rewind_mode::active` instead of `optional`.

**Comment by aneax** [comment]
You are correct about violation of **the failing rule should not consume the input**. The rule is incorrect when used with `seq`, for example.

However, since `sor` tries to match until one of the rules succeeds, it has `rewind_mode::required` except for the last rule.

https://github.com/taocpp/PEGTL/blob/3c6e0e092ca77868ea3a0b0f47b5948dc07c1c86/include/tao/pegtl/internal/sor.hpp#L45

Shouldn't `sor` mark and rewind to the marked point when the first rule fails without the failed rule needing to additionally mark and perform the rewind?

This is the code that is confusing me when called from `sor`.

https://github.com/taocpp/PEGTL/blob/3c6e0e092ca77868ea3a0b0f47b5948dc07c1c86/include/tao/pegtl/match.hpp#L138-L142

Even when rewind_mode `M` is `rewind_mode::required`, why the marker `m`
only uses `use_guard` to decide marking type disregarding the value of `M`?

**Comment by ColinH** [comment]
> Shouldn't sor mark and rewind to the marked point when the first rule fails without the failed rule needing to additionally mark and perform the rewind?

That would make things easier, but it would also be needlessly inefficient. We optimised the PEGTL to make sure that a non-dummy `rewind_guard` is only created when it is really needed.

(The "non-dummy" part depends on the `rewind_mode` given as template argument to `rewind_guard`; if you look at its source you'll see that a `rewind_guard` with `rewind_mode::optional` does nothing, and will - hopefully - be completely "optimised away" by the compiler.)

When `sor` calls its sub-rules with `rewind_mode::required` it is _telling_ them that rewinding is needed. Some rules, like your custom rule, need a `rewind_guard` with the current `rewind_mode` to perform rewinding - when necessary, i.e. when it is not in the scope of a different `rewind_guard` that would rewind to the same point on failure.

Other rules like `at` unconditionally rewind and therefore always use a rewind guard. They pass `rewind_mode::optional` to their sub-rules to let those rules know that they don't need to rewind themselves.

Then there are rules like `string` and `one` that inherently only consume on success and therefore don't need any `rewind_guard` to rewind on failure.

If `sor` were to unconditionally create a non-dummy rewind-guard it would be doing extra redundant work for the last two of these three cases, and that's what we wanted to avoid.

Similarly `match()` only creates a `rewind_guard` when it might need to rewind (`has_apply0_bool`) or when it needs to remember where it started matching to create an `action_input` to call an action (`has_apply`). Otherwise it might be redundant in case the called rule doesn't need it.

But, again, when `match()` *does* create a "real" `rewind_guard` it lets the rule it calls know so that it can optimise based on that knowledge - usually via the template paramater in the call to `in.auto_rewind`.

**Comment by aneax** [comment]
Thanks for the detailed explanation. I realised my understanding of `rewind_mode` was different from what it actually meant.
