### ISSUE TITLE
MAP_FILE

### ISSUE THREAD

**Issue by okeyes-r7** [taocpp/PEGTL#62]
`PEGTL` uses the MAP_FILE compatibility flag - according to the Linux standard this is [ignored](http://man7.org/linux/man-pages/man2/mmap.2.html). Worth removing?

**Comment by ColinH** [comment]
Since `MAP_FILE` is the default on macOS, and doesn't seem to exist on Solaris, which I just checked for the heck of it, you are probably right... I'll remove it until either one of the automated test or a user complains. Thanks for pointing this out, hope you are having fun digging around the source :-)

**Comment by okeyes-r7** [comment]
Eh, little bit 'fun', little bit 'submitted a wrapper to CRAN, who have incredibly pedantic expectations for compiled code'. Apparently there's some interesting valgrind doohickies around numerical calculations, which I'll dig into this evening and hopefully have a vaguely useful PR in soon enough!
