### ISSUE TITLE
opening files with non-ANSI filenames on Windows

### ISSUE THREAD

**Issue by wojdyr** [taocpp/PEGTL#78]
Thank you for maintaining PEGTL.
My understanding is that currently file_input and read_input don't work with Unicode filenames on Windows? Because I see that internal::file_reader uses fopen(_s) not _wfopen(_s).
If that's true, this is a feature request to add support for Unicode filenames.

**Comment by ColinH** [comment]
Are you saying that `fopen` on Windows only accepts ASCII, but not Unicode encoded as UTF-8? What does `wfopen` get as argument, a string or a wide string? What type and encoding?

**Comment by wojdyr** [comment]
`fopen` takes filename in Windows (ANSI) code page, which is ASCII + 128 extra characters.

`_wfopen` takes `wchar_t *` which is either UCS2 or UTF-16 (I don't know).

I don't have a lot of experience with it, but I came across one example of a library handling this issue: zlib has an extra function `gzopen_w` which does the same as `gzopen` but takes `wchar_t*` as an argument and exists only on Windows.

**Comment by skyrich62** [comment]
FYI:
https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx

> FILE *fopen(   
>    const char *filename,  
>    const char *mode   
> );  
> FILE *_wfopen(   
>    const wchar_t *filename,  
>    const wchar_t *mode   
> );

**Comment by ColinH** [comment]
Using `_wfopen()` instead of `fopen()` is easy, the problem is that we also store the filename as `source`, i.e. name-of-the-source-of-the-parsed-data.

This can currently be a `const char *`, or a `std::string, so that we can construct the `std::string` in the `position` in the `parse_error` exception class.

The question is, (how) can we use `_wfopen()` without supporting `wchar_t` or `std::wstring` as `source`?

Can we convert the wide characters provided to `_fopen()` to a regular string - or do we have to bite the bullet and enable wide strings in `parse_error` etc...?

**Comment by ColinH** [comment]
@skyrich62 Thanks for the link; at the moment we are just looking at the encoding of the file name, not the content, but we'll keep the possibility of an on-the-fly conversion in mind.

**Comment by d-frey** [comment]
As a work-around for this: Would it be sufficient to add a ctor taking the `FILE*` directly and accept an additional "normal" `std::string` as the source? It makes usage slightly more verbose, but I think it fits better with the rest of the design.

@wojdyr Would that be OK with you or does it cause additional problems? Note that our class takes ownership of the `FILE*`, e.g. it closes it during destruction.

**Comment by wojdyr** [comment]
Yes, it would work fine for me.

**Comment by ColinH** [comment]
That makes things easier, `read_input` now has a constructor that takes a `FILE*` as first argument.

**Comment by wojdyr** [comment]
Thanks!
